services:
  thehive:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: thehive-backend
    ports:
      - "8080"
    volumes:
      - ./backend/uploads/images:/app/uploads/images
    depends_on:
      hive-db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: thehive-frontend
    ports:
      - "80:5173"
    volumes:
      - ./frontend:/app
      - frontend-node_modules:/app/node_modules
    depends_on:
      - thehive

  hive-db:
    image: mysql:8.4
    container_name: hive-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: hive-db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306"
    volumes:
      - hive-db-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-padmin" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  hive-db-data:
  frontend-node_modules:
