spring.application.name=thehive

spring.datasource.url=jdbc:mysql://hive-db:3306/hive-db
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db